plugins {
    id "com.android.application"
}

android {
    namespace "br.com.wondertravel.passagens"
    compileSdk 35

    defaultConfig {
        applicationId "br.com.wondertravel.monitor.v5"
        minSdk 26
        targetSdk 34
        versionCode 10
        versionName "0.10.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
